# Parses the .ent files from http://www.w3.org/TR/xhtml1/#h-A2

import glob, re

outfile = open("htmlentitymap.cpp", "wt")
outfile.write(
"""#include "stdafx.h"

// This file is automatically generated. Do not edit it.

QHash<QString, QChar> getHtmlEntityMap()
{
	QHash<QString, QChar> h;

""")

r = re.compile(r'<!ENTITY (\S*)\s*\"&#([0-9]*);\">.*')

for fname in glob.iglob("*.ent"):
	for line in open(fname, "rt"):
		match = r.match(line)
		if match:
			outfile.write( '\th.insert("%s", QChar(%s));\n' % (match.group(1), match.group(2)) )

outfile.write("""
	h.insert("amp", QChar('&'));
	h.insert("lt", QChar('<'));
	return h;
}
""")
